import { z } from 'zod';
import {
  httpsStoreUrlSchema,
  woocommerceOnboardingCredentialsSchema,
} from './onboarding.js';

export const woocommercePairingCreateSchema = z
  .object({
    storeUrl: httpsStoreUrlSchema,
  })
  .strict();
export type WoocommercePairingCreate = z.infer<
  typeof woocommercePairingCreateSchema
>;

export const woocommercePairingCreatedResponseSchema = z
  .object({
    pairing: z
      .object({
        id: z.string().uuid(),
        provider: z.literal('woocommerce'),
        storeUrl: z.string().min(1).max(2048),
        pairingToken: z.string().min(32).max(128),
        expiresAt: z.string().datetime(),
      })
      .strict(),
  })
  .strict();
export type WoocommercePairingCreatedResponse = z.infer<
  typeof woocommercePairingCreatedResponseSchema
>;

/**
 * Sent server-side by the ShopAI WordPress plugin on the merchant's
 * WooCommerce host. The pairing token travels in the
 * `x-shopai-pairing-token` header, never in the URL, and the raw WooCommerce
 * API key generated by the plugin only exists in this request body — it is
 * never rendered to a browser or persisted outside the secret backend.
 */
export const woocommercePairingCompleteSchema = z
  .object({
    siteUrl: httpsStoreUrlSchema,
    siteName: z.string().trim().min(1).max(256),
    wpVersion: z.string().trim().max(64).optional(),
    wooVersion: z.string().trim().max(64).optional(),
    credentials: woocommerceOnboardingCredentialsSchema,
  })
  .strict();
export type WoocommercePairingComplete = z.infer<
  typeof woocommercePairingCompleteSchema
>;

export const woocommercePairingCompleteResponseSchema = z
  .object({
    connection: z
      .object({
        id: z.string().uuid(),
        provider: z.literal('woocommerce'),
        authorizationStatus: z.enum(['pending', 'active']),
        syncMode: z.enum(['full', 'incremental']),
      })
      .strict(),
    store: z
      .object({
        url: z.string().min(1).max(2048),
        name: z.string().min(1).max(256),
      })
      .strict(),
    mode: z.enum(['connected', 'reconnected']),
  })
  .strict();
export type WoocommercePairingCompleteResponse = z.infer<
  typeof woocommercePairingCompleteResponseSchema
>;
